# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eeab6409d92c5190c4b5ae7cabd6f5e7bc5f997673f50b4606728351ef242dbbdf814eaf80a7dedaf4fa3178e8ff9750b7cc638942b678d84f6d8cbf15f6bc13

test:
  secret_key_base: 33dc08afb72197445931b7826aac37f082014d5dc51f10815e9cb126154d95ae617fb261e0ef9fc7c971e202c4b2e887ed43d22d51f94c5c9ee4109c2dbaad7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
